// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgabnhzlakrsnckjqnfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnYWJuaHpsYWtyc25ja2pxbmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDY1ODgsImV4cCI6MjA2NTQyMjU4OH0.yIfMYTC_zpnTKwnYxM_hHwakTi_Rg-IjmFC1Z5JBPVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);